"""Constants for all stock analyzers"""

# Base Analyzer Constants
SCORE_STRONG_BUY_THRESHOLD = 0.8
SCORE_BUY_THRESHOLD = 0.6
SCORE_HOLD_THRESHOLD = 0.4
SCORE_SELL_THRESHOLD = 0.2
TARGET_PRICE_MULTIPLIER = 1.10  # 10% increase for buy recommendations

# Default Analysis Values
DEFAULT_SCORE = 0.5
DEFAULT_CONFIDENCE = 0.5
DEFAULT_REASONING = "No analysis available"
DEFAULT_NO_ANALYZERS_REASONING = "No analyzers configured"
DEFAULT_NO_ANALYZERS_CONFIDENCE = 0.0

# Score Normalization
MIN_SCORE = 0.0
MAX_SCORE = 1.0

# News Analyzer Constants
NEWS_COUNT_THRESHOLD = 5
RECENT_NEWS_DAYS = 30  # Increased from 7 to 30 days for better historical context
NEWS_ARTICLES_TO_CHECK = 100  # Increased from 50 to 100 articles for LLM analysis
NEWS_ARTICLES_PER_SOURCE = 100  # Articles to fetch per source (increased from 50)
NEWS_RELATED_MARKET_ARTICLES = 50  # Additional articles from related market topics
NEWS_SENTIMENT_MULTIPLIER = 1.5
NEWS_CONFIDENCE_BASE = 0.5
NEWS_CONFIDENCE_NO_NEWS = 0.3
NEWS_CONFIDENCE_MAX = 0.8  # Increased confidence with more sources
NEWS_CONFIDENCE_ERROR = 0.2
NEWS_SCORE_HIGH_ACTIVITY = 0.15
NEWS_SCORE_POSITIVE_SENTIMENT = 0.2
NEWS_SCORE_NEGATIVE_SENTIMENT = -0.2
NEWS_CONFIDENCE_CALCULATION_DIVISOR = 20
NEWS_LLM_CONFIDENCE_BOOST = 0.1  # Additional confidence when using LLM

# News Keywords
POSITIVE_KEYWORDS = [
    'growth', 'profit', 'gain', 'upgrade', 'beat', 'surge',
    'rally', 'soar', 'strong', 'positive', 'bullish', 'buy'
]
NEGATIVE_KEYWORDS = [
    'decline', 'loss', 'drop', 'downgrade', 'miss', 'fall',
    'crash', 'plunge', 'weak', 'negative', 'bearish', 'sell'
]

# Volume Analyzer Constants
VOLUME_HIGH_THRESHOLD = 1_000_000
VOLUME_VERY_HIGH_THRESHOLD = 10_000_000
VOLUME_LOW_THRESHOLD = 100_000
VOLUME_CONFIDENCE = 0.6
VOLUME_SCORE_VERY_HIGH = 0.3
VOLUME_SCORE_HIGH = 0.2
VOLUME_SCORE_LOW = -0.2
VOLUME_SCORE_BULLISH_SIGNAL = 0.15
VOLUME_SCORE_BEARISH_SIGNAL = -0.15
VOLUME_PRICE_CHANGE_THRESHOLD = 1.0

# Technical Strategy Analyzer Constants
RSI_PERIOD = 14
SMA_SHORT = 20
SMA_LONG = 50
TECHNICAL_HISTORY_PERIOD = "3mo"
TECHNICAL_MIN_DATA_LENGTH = 50
TECHNICAL_CONFIDENCE = 0.65
TECHNICAL_CONFIDENCE_INSUFFICIENT_DATA = 0.3
TECHNICAL_CONFIDENCE_ERROR = 0.2
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_NEUTRAL_LOW = 40
RSI_NEUTRAL_HIGH = 60
TECHNICAL_SCORE_OVERSOLD = 0.2
TECHNICAL_SCORE_OVERBOUGHT = -0.2
TECHNICAL_SCORE_NEUTRAL_RSI = 0.1
TECHNICAL_SCORE_GOLDEN_CROSS = 0.15
TECHNICAL_SCORE_DEATH_CROSS = -0.15
TECHNICAL_SCORE_ABOVE_MA = 0.1
TECHNICAL_SCORE_BELOW_MA = -0.1
TECHNICAL_SCORE_NEAR_HIGHS = 0.1
TECHNICAL_SCORE_NEAR_LOWS = -0.05
TECHNICAL_RECENT_PERIOD = 20

# Fundamental Analyzer Constants
FUNDAMENTAL_CONFIDENCE = 0.6
FUNDAMENTAL_CONFIDENCE_ERROR = 0.3

# P/E Ratio Thresholds
PE_RATIO_MIN = 10
PE_RATIO_MAX = 20
PE_RATIO_HIGH = 30
FUNDAMENTAL_SCORE_PE_ATTRACTIVE = 0.15
FUNDAMENTAL_SCORE_PE_VERY_LOW = 0.2
FUNDAMENTAL_SCORE_PE_HIGH = -0.15

# P/B Ratio Thresholds
PB_RATIO_LOW = 1
PB_RATIO_REASONABLE = 3
PB_RATIO_HIGH = 5
FUNDAMENTAL_SCORE_PB_LOW = 0.15
FUNDAMENTAL_SCORE_PB_REASONABLE = 0.1
FUNDAMENTAL_SCORE_PB_HIGH = -0.1

# Debt-to-Equity Thresholds
DEBT_TO_EQUITY_LOW = 50
DEBT_TO_EQUITY_HIGH = 100
FUNDAMENTAL_SCORE_DEBT_LOW = 0.1
FUNDAMENTAL_SCORE_DEBT_HIGH = -0.1

# Profit Margin Thresholds
PROFIT_MARGIN_STRONG = 0.15  # 15%
PROFIT_MARGIN_GOOD = 0.10  # 10%
FUNDAMENTAL_SCORE_MARGIN_STRONG = 0.15
FUNDAMENTAL_SCORE_MARGIN_GOOD = 0.1
FUNDAMENTAL_SCORE_MARGIN_NEGATIVE = -0.15

# Revenue Growth Thresholds
REVENUE_GROWTH_STRONG = 0.20  # 20%
REVENUE_GROWTH_GOOD = 0.10  # 10%
REVENUE_GROWTH_DECLINING = -0.10  # -10%
FUNDAMENTAL_SCORE_REVENUE_STRONG = 0.15
FUNDAMENTAL_SCORE_REVENUE_GOOD = 0.1
FUNDAMENTAL_SCORE_REVENUE_DECLINING = -0.15

# Earnings Growth Thresholds
EARNINGS_GROWTH_STRONG = 0.25  # 25%
EARNINGS_GROWTH_GOOD = 0.10  # 10%
EARNINGS_GROWTH_DECLINING = -0.20  # -20%
FUNDAMENTAL_SCORE_EARNINGS_STRONG = 0.15
FUNDAMENTAL_SCORE_EARNINGS_GOOD = 0.1
FUNDAMENTAL_SCORE_EARNINGS_DECLINING = -0.15

# Dividend Yield Thresholds
DIVIDEND_YIELD_ATTRACTIVE = 0.04  # 4%
DIVIDEND_YIELD_MODERATE = 0.02  # 2%
FUNDAMENTAL_SCORE_DIVIDEND_ATTRACTIVE = 0.1
FUNDAMENTAL_SCORE_DIVIDEND_MODERATE = 0.05

# Market Cap Thresholds
MARKET_CAP_LARGE = 10e9  # $10 billion
FUNDAMENTAL_SCORE_LARGE_CAP = 0.05

# Momentum Analyzer Constants
MOMENTUM_HISTORY_PERIOD = "6mo"
MOMENTUM_MIN_DATA_LENGTH = 30
MOMENTUM_CONFIDENCE = 0.7
MOMENTUM_CONFIDENCE_INSUFFICIENT_DATA = 0.3
MOMENTUM_CONFIDENCE_ERROR = 0.2
MOMENTUM_PERIOD_5D = 5
MOMENTUM_PERIOD_20D = 20
MOMENTUM_PERIOD_60D = 60

# Short-term Momentum Thresholds (5 days)
MOMENTUM_5D_STRONG_POSITIVE = 3.0
MOMENTUM_5D_POSITIVE = 1.0
MOMENTUM_5D_STRONG_NEGATIVE = -3.0
MOMENTUM_5D_NEGATIVE = -1.0
MOMENTUM_SCORE_5D_STRONG_POSITIVE = 0.2
MOMENTUM_SCORE_5D_POSITIVE = 0.1
MOMENTUM_SCORE_5D_STRONG_NEGATIVE = -0.2
MOMENTUM_SCORE_5D_NEGATIVE = -0.1

# Medium-term Momentum Thresholds (20 days)
MOMENTUM_20D_STRONG_POSITIVE = 5.0
MOMENTUM_20D_POSITIVE = 2.0
MOMENTUM_20D_STRONG_NEGATIVE = -5.0
MOMENTUM_20D_NEGATIVE = -2.0
MOMENTUM_SCORE_20D_STRONG_POSITIVE = 0.15
MOMENTUM_SCORE_20D_POSITIVE = 0.1
MOMENTUM_SCORE_20D_STRONG_NEGATIVE = -0.15
MOMENTUM_SCORE_20D_NEGATIVE = -0.1

# Long-term Momentum Thresholds (60 days)
MOMENTUM_60D_STRONG_POSITIVE = 10.0
MOMENTUM_60D_POSITIVE = 5.0
MOMENTUM_60D_STRONG_NEGATIVE = -10.0
MOMENTUM_60D_NEGATIVE = -5.0
MOMENTUM_SCORE_60D_STRONG_POSITIVE = 0.15
MOMENTUM_SCORE_60D_POSITIVE = 0.1
MOMENTUM_SCORE_60D_STRONG_NEGATIVE = -0.15
MOMENTUM_SCORE_60D_NEGATIVE = -0.1

# Momentum Consistency
MOMENTUM_SCORE_CONSISTENT_POSITIVE = 0.1
MOMENTUM_SCORE_CONSISTENT_NEGATIVE = -0.1
MOMENTUM_SCORE_ACCELERATING = 0.1
MOMENTUM_SCORE_DECELERATING = -0.1

# Price Analyzer Constants
PRICE_MOMENTUM_THRESHOLD = 2.0
PRICE_PE_RATIO_MIN = 10
PRICE_PE_RATIO_MAX = 25
PRICE_PE_RATIO_HIGH = 30
PRICE_CONFIDENCE = 0.7
PRICE_SCORE_STRONG_POSITIVE = 0.25
PRICE_SCORE_POSITIVE = 0.1
PRICE_SCORE_STRONG_NEGATIVE = -0.25
PRICE_SCORE_NEGATIVE = -0.1
PRICE_SCORE_REASONABLE_VALUATION = 0.2
PRICE_SCORE_UNDERVALUED = 0.15
PRICE_SCORE_OVERVALUED = -0.15
PRICE_SCORE_SIGNIFICANT_INCREASE = 0.1
PRICE_SCORE_SIGNIFICANT_DECREASE = -0.1
PRICE_CHANGE_THRESHOLD = 0.5
PRICE_MULTIPLIER_HIGH = 1.05
PRICE_MULTIPLIER_LOW = 0.95

# Support/Resistance Analyzer Constants
SR_LOOKBACK_PERIOD = '6mo'
SR_SUPPORT_TOLERANCE = 0.02  # 2%
SR_RESISTANCE_TOLERANCE = 0.02  # 2%
SR_MIN_TOUCHES = 2
SR_MIN_DATA_LENGTH = 20
SR_CONFIDENCE = 0.65
SR_CONFIDENCE_INSUFFICIENT_DATA = 0.3
SR_CONFIDENCE_NO_LEVELS = 0.4
SR_CONFIDENCE_ERROR = 0.2
SR_DISTANCE_VERY_CLOSE = 2.0  # 2%
SR_DISTANCE_CLOSE = 5.0  # 5%
SR_DISTANCE_NEAR = 3.0  # 3%
SR_SCORE_NEAR_SUPPORT_VERY_CLOSE = 0.25
SR_SCORE_NEAR_SUPPORT_CLOSE = 0.15
SR_SCORE_NEAR_RESISTANCE_VERY_CLOSE = -0.2
SR_SCORE_NEAR_RESISTANCE_CLOSE = -0.1
SR_SCORE_NEAR_SUPPORT_NEAR = 0.2
SR_SCORE_NEAR_RESISTANCE_NEAR = -0.15
SR_RISK_REWARD_FAVORABLE = 2.0
SR_RISK_REWARD_POOR = 0.5
SR_SCORE_FAVORABLE_RR = 0.15
SR_SCORE_POOR_RR = -0.1

# Volatility Analyzer Constants
VOLATILITY_LOW_THRESHOLD = 0.15  # 15% annualized
VOLATILITY_HIGH_THRESHOLD = 0.35  # 35% annualized
VOLATILITY_HISTORY_PERIOD = "3mo"
VOLATILITY_MIN_DATA_LENGTH = 20
VOLATILITY_MIN_DATA_LENGTH_TREND = 40
VOLATILITY_CONFIDENCE = 0.65
VOLATILITY_CONFIDENCE_INSUFFICIENT_DATA = 0.3
VOLATILITY_CONFIDENCE_ERROR = 0.2
TRADING_DAYS_PER_YEAR = 252
VOLATILITY_TREND_DECREASING = 0.8
VOLATILITY_TREND_INCREASING = 1.2
VOLATILITY_SCORE_LOW = 0.1
VOLATILITY_SCORE_HIGH = -0.15
VOLATILITY_SCORE_DECREASING = 0.1
VOLATILITY_SCORE_INCREASING = -0.1
VOLATILITY_SCORE_TIGHT_RANGE = 0.05
VOLATILITY_SCORE_WIDE_RANGE = -0.1
VOLATILITY_RANGE_TIGHT = 20.0  # 20%
VOLATILITY_RANGE_WIDE = 50.0  # 50%
VOLATILITY_RECENT_PERIOD = 20

# Period-Based Analyzer Constants
PERIOD_BASED_CONFIDENCE = 0.7
PERIOD_BASED_CONFIDENCE_ERROR = 0.3

# Period Configuration
PERIODS_CONFIG = {
    '1w': {'period': '5d', 'weight': 0.2, 'name': '1 Week'},
    '1mo': {'period': '1mo', 'weight': 0.3, 'name': '1 Month'},
    '3mo': {'period': '3mo', 'weight': 0.3, 'name': '3 Months'},
    '6mo': {'period': '6mo', 'weight': 0.2, 'name': '6 Months'}
}

# Period Change Thresholds
PERIOD_CHANGE_STRONG_POSITIVE = 5.0
PERIOD_CHANGE_POSITIVE = 2.0
PERIOD_CHANGE_NEGATIVE = -2.0
PERIOD_CHANGE_STRONG_NEGATIVE = -5.0

# Period Scores
PERIOD_SCORE_STRONG_POSITIVE = 0.8
PERIOD_SCORE_POSITIVE = 0.65
PERIOD_SCORE_SLIGHTLY_POSITIVE = 0.55
PERIOD_SCORE_SLIGHTLY_NEGATIVE = 0.45
PERIOD_SCORE_NEGATIVE = 0.35
PERIOD_SCORE_STRONG_NEGATIVE = 0.2

# Period Recommendations
PERIOD_REC_BUY = "BUY"
PERIOD_REC_HOLD = "HOLD"
PERIOD_REC_SELL = "SELL"

# Consensus Thresholds
CONSENSUS_BUY_COUNT_STRONG = 3
CONSENSUS_BUY_COUNT_MODERATE = 2
CONSENSUS_SELL_COUNT_STRONG = 3
CONSENSUS_SELL_COUNT_MODERATE = 2
CONSENSUS_SCORE_STRONG_BUY = 0.7
CONSENSUS_SCORE_BUY = 0.65
CONSENSUS_SCORE_STRONG_SELL = 0.3
CONSENSUS_SCORE_SELL = 0.35

# Composite Analyzer Constants
COMPOSITE_DEFAULT_SCORE = 0.5
COMPOSITE_DEFAULT_CONFIDENCE = 0.0

